# Generated by Django 6.0.3 on 2026-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="previews/"),
        ),
    ]
