# Generated by Django 6.0.3 on 2026-03-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_paper_preview_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paper",
            old_name="preview_image",
            new_name="preview",
        ),
    ]
